// Procedural ambient audio for the Backrooms — no audio files.
//
// Layers:
//   - Brown-noise bed: the deep, rounded room-tone rumble the mythos is known
//     for. Generated by integrating white noise into a looping buffer.
//   - Fluorescent hum: 60 Hz + 120 Hz tones whose gain is coupled to the light
//     flicker, so the buzz dips and swells together with the visuals.
//
// The AudioContext is created lazily on a user gesture (browsers block audio
// otherwise), and suspended/resumed with pointer lock and tab visibility.
// A single master gain drives mute/volume, persisted to localStorage.

const LS_MUTED = "backrooms.audio.muted";
const LS_VOLUME = "backrooms.audio.volume";
const BED_LEVEL = 0.9; // the brown-noise bed's normal gain (see start())

// Fill a buffer with brown (Brownian) noise: a running integral of white noise.
// A one-pole low-pass then shaves the residual high-frequency fizz so the bed
// is a smooth rumble rather than a grainy hiss; the result is normalised so the
// smoothing doesn't change perceived loudness.
function fillBrownNoise(buffer) {
  for (let ch = 0; ch < buffer.numberOfChannels; ch++) {
    const data = buffer.getChannelData(ch);
    let last = 0;
    let smooth = 0;
    let peak = 0;
    for (let i = 0; i < data.length; i++) {
      const white = Math.random() * 2 - 1;
      // Leaky integrator → brown noise (deeper leak = smoother, bassier).
      last = (last + 0.015 * white) / 1.015;
      // One-pole low-pass to smooth out remaining high-frequency crackle.
      smooth += 0.08 * (last - smooth);
      data[i] = smooth;
      const a = Math.abs(smooth);
      if (a > peak) peak = a;
    }
    const norm = peak > 0 ? 0.9 / peak : 1;
    for (let i = 0; i < data.length; i++) data[i] *= norm;
  }
}

export class Ambience {
  constructor() {
    this.ctx = null;
    this.started = false;
    this.master = null;
    this.humGain = null;
    this.bedGain = null;
    this.reactivity = 0;

    this.muted = localStorage.getItem(LS_MUTED) === "1";
    const v = parseFloat(localStorage.getItem(LS_VOLUME));
    this.volume = Number.isFinite(v) ? v : 0.22; // low by default
  }

  // Build the graph. Must be called from a user gesture (e.g. the start click).
  start() {
    if (this.started) {
      // Already built — just make sure we're running.
      this.resume();
      return;
    }
    const Ctx = window.AudioContext || window.webkitAudioContext;
    if (!Ctx) return;
    this.ctx = new Ctx();
    const ctx = this.ctx;

    // Master bus → destination.
    this.master = ctx.createGain();
    this.master.gain.value = this.muted ? 0 : this.volume;
    this.master.connect(ctx.destination);

    // Analyser tap (for verification / future reactive visuals).
    this.analyser = ctx.createAnalyser();
    this.analyser.fftSize = 2048;
    this.master.connect(this.analyser);

    // Brown-noise bed: a few seconds, looped seamlessly.
    const bedBuffer = ctx.createBuffer(1, ctx.sampleRate * 4, ctx.sampleRate);
    fillBrownNoise(bedBuffer);
    const bed = ctx.createBufferSource();
    bed.buffer = bedBuffer;
    bed.loop = true;
    this.bedGain = ctx.createGain();
    this.bedGain.gain.value = BED_LEVEL;
    // Roll off the very top so the bed stays a warm rumble, not a hiss.
    const bedFilter = ctx.createBiquadFilter();
    bedFilter.type = "lowpass";
    bedFilter.frequency.value = 340;
    bed.connect(bedFilter).connect(this.bedGain).connect(this.master);
    bed.start();

    // Fluorescent hum: mains-style tone + harmonic, gently filtered.
    this.humGain = ctx.createGain();
    this.humGain.gain.value = 0.0; // driven by setFlicker()
    const humFilter = ctx.createBiquadFilter();
    humFilter.type = "lowpass";
    humFilter.frequency.value = 400;
    humFilter.connect(this.humGain).connect(this.master);
    for (const [freq, level] of [
      [60, 0.06],
      [120, 0.03],
    ]) {
      const osc = ctx.createOscillator();
      osc.type = "sawtooth";
      osc.frequency.value = freq;
      const g = ctx.createGain();
      g.gain.value = level;
      osc.connect(g).connect(humFilter);
      osc.start();
    }

    this.started = true;
  }

  // Couple the hum to the light flicker (0.35..1.1 from the render loop). The
  // reactivity term lets later features (leaked zones) swell the ambience.
  setFlicker(f) {
    if (!this.humGain) return;
    const base = 0.25 + 0.75 * Math.min(1, Math.max(0, f));
    this.humGain.gain.value = base * (1 + this.reactivity * 0.8);
  }

  // Hook for later systems (the leak, entity zones) to color the mix. 0..1.
  setReactivity(amount) {
    this.reactivity = Math.min(1, Math.max(0, amount));
  }

  // RMS of the current master output — non-zero means sound is flowing.
  level() {
    if (!this.analyser) return 0;
    const buf = new Float32Array(this.analyser.fftSize);
    this.analyser.getFloatTimeDomainData(buf);
    let sum = 0;
    for (let i = 0; i < buf.length; i++) sum += buf[i] * buf[i];
    return Math.sqrt(sum / buf.length);
  }

  // Fraction of spectral energy in the low band (< ~500 Hz). Brown noise + hum
  // should be strongly low-dominant.
  lowBandRatio() {
    if (!this.analyser || !this.ctx) return 0;
    const bins = new Uint8Array(this.analyser.frequencyBinCount);
    this.analyser.getByteFrequencyData(bins);
    const nyquist = this.ctx.sampleRate / 2;
    const cutoffBin = Math.floor((500 / nyquist) * bins.length);
    let low = 0;
    let total = 0;
    for (let i = 0; i < bins.length; i++) {
      total += bins[i];
      if (i <= cutoffBin) low += bins[i];
    }
    return total > 0 ? low / total : 0;
  }

  resume() {
    if (this.ctx && this.ctx.state === "suspended") this.ctx.resume();
  }

  suspend() {
    if (this.ctx && this.ctx.state === "running") this.ctx.suspend();
  }

  toggleMute() {
    this.setMuted(!this.muted);
    return this.muted;
  }

  setMuted(muted) {
    this.muted = muted;
    localStorage.setItem(LS_MUTED, muted ? "1" : "0");
    if (this.master && this.ctx) {
      // Ramp to avoid clicks.
      const target = muted ? 0.0001 : this.volume;
      this.master.gain.setTargetAtTime(target, this.ctx.currentTime, 0.05);
    }
  }

  // Silence just the brown-noise "static" bed, independent of the fluorescent
  // hum and the mute toggle — used for areas that shouldn't carry the main
  // game's room-tone rumble, like Stage 2.
  muteBed() {
    if (!this.bedGain || !this.ctx) return;
    this.bedGain.gain.setTargetAtTime(0.0001, this.ctx.currentTime, 0.2);
  }

  unmuteBed() {
    if (!this.bedGain || !this.ctx) return;
    this.bedGain.gain.setTargetAtTime(BED_LEVEL, this.ctx.currentTime, 0.2);
  }
}
